apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-argo-rollouts
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.0.2'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the Argo Rollouts progressive delivery controller Helm chart.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-argo-rollouts

    Installs Argo Rollouts for progressive delivery (canary, blue-green deployments) using Crossplane and the Helm provider.
  repository: ghcr.io/hops-ops/helm-argo-rollouts
  source: github.com/hops-ops/helm-argo-rollouts
